name: AutoBuild

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore ArchiSteamFarm/ASFItemDropper.sln

    - name: Build
      run: dotnet build ArchiSteamFarm/ASFItemDropper.sln --no-restore --configuration Release

    - name: Run tests
      run: dotnet test ArchiSteamFarm/ASFItemDropper.sln --no-build --verbosity normal
